# Chapter 11. General Linear Models and Least Squares

## General Linear Models

#### A statistical model is a set of equations that relates predictors (called independent variables) to observations (called the dependent variable). In the model of the stock market, the independent variable is time and the dependent variable is stock market price (e.g., quantified as the S&P 500 index).

In [4]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

X= np.vstack([np.ones(x.shape[0]), x]).T

print(X)
XTX = np.dot(X.T, X)
print("X^T X matrix:\n", XTX)

XTX_inv = np.linalg.inv(XTX)
print("\nInverse of X^T X matrix (X^T X)^-1:\n", XTX_inv)

beta = np.dot(XTX_inv, np.dot(X.T, y))
print("\nEstimated coefficients (beta):\n", beta)

print(f"\nThe linear regression equation is: y = {beta[0]:.2f} + {beta[1]:.2f}x")

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]]
X^T X matrix:
 [[ 5. 15.]
 [15. 55.]]

Inverse of X^T X matrix (X^T X)^-1:
 [[ 1.1 -0.3]
 [-0.3  0.1]]

Estimated coefficients (beta):
 [2.2 0.6]

The linear regression equation is: y = 2.20 + 0.60x
