##  Row Reduction and LU Decomposition

#### Memorize this statement: The goal of row reduction is to transform a dense matrix into an upper-triangular matrix

## LU Decomposition
#### The “LU” in LU decomposition stands for “lower upper,” as in lower-triangular, upper-triangular. The idea is to decompose a matrix into the product of two triangular matrices:


In [2]:
import scipy.linalg
import numpy as np

A = np.array([ [2,2,4], [1,0,3], [2,1,2] ])
_,L,U = scipy.linalg.lu(A)

# print them out
print('L: '), print(L)
print('U: '), print(U)

L: 
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]]
U: 
[[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]


(None, None)

## Exercise 10-2.
#### Use the matrix-multiplication method to make a rank-3 matrix. Take its LU decomposition, and show the three matrices with their ranks in the title, as in Figure 10-2. Notice the ranks of the three matrices and that has all 1s on the diagonal. Feel free to explore the ranks of matrices with other sizes and ranks.

In [ ]:
## 