##  Row Reduction and LU Decomposition

#### Memorize this statement: The goal of row reduction is to transform a dense matrix into an upper-triangular matrix

## LU Decomposition
#### The “LU” in LU decomposition stands for “lower upper,” as in lower-triangular, upper-triangular. The idea is to decompose a matrix into the product of two triangular matrices:


In [2]:
import scipy.linalg
import numpy as np

A = np.array([ [2,2,4], [1,0,3], [2,1,2] ])
_,L,U = scipy.linalg.lu(A)

# print them out
print('L: '), print(L)
print('U: '), print(U)

L: 
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  1.  1. ]]
U: 
[[ 2.  2.  4.]
 [ 0. -1.  1.]
 [ 0.  0. -3.]]


(None, None)

## Exercise 10-2.
#### Use the matrix-multiplication method to make a rank-3 matrix. Take its LU decomposition, and show the three matrices with their ranks in the title, as in Figure 10-2. Notice the ranks of the three matrices and that has all 1s on the diagonal. Feel free to explore the ranks of matrices with other sizes and ranks.

In [3]:
from scipy.linalg import lu

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [2, 4, 6, 8]]) 

P, L, U = lu(A)
rank_A = np.linalg.matrix_rank(A)
rank_L = np.linalg.matrix_rank(L)
rank_U = np.linalg.matrix_rank(U)

print("Matrix A:\n", A)
print("Rank of A:", rank_A)
print("\nLower Triangular Matrix L:\n", L)
print("Rank of L:", rank_L)
print("\nUpper Triangular Matrix U:\n", U)
print("Rank of U:", rank_U)

Matrix A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 2  4  6  8]]
Rank of A: 2

Lower Triangular Matrix L:
 [[1.         0.         0.         0.        ]
 [0.22222222 1.         0.         0.        ]
 [0.55555556 0.25       1.         0.        ]
 [0.11111111 0.5        0.         1.        ]]
Rank of L: 4

Upper Triangular Matrix U:
 [[9.00000000e+00 1.00000000e+01 1.10000000e+01 1.20000000e+01]
 [0.00000000e+00 1.77777778e+00 3.55555556e+00 5.33333333e+00]
 [0.00000000e+00 0.00000000e+00 1.60365548e-16 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]]
Rank of U: 2
