## Dot Product

- The dot product can be interpreted as a measure of similarity or mapping between two vectors. Imagine that you collected height and weight data from 20 people, and you stored those data in two vectors. You would certainly expect those variables to be related to each other (taller people tend to weigh more), and therefore you could expect the dot product between those two vectors to be large. On the other hand, the magnitude of the dot product depends on the scale of the data, which means the dot product between data measured in grams and centimeters would be larger than the dot product between data measured in pounds and feet. This arbitrary scaling, however, can be eliminated with a normalization factor. In fact, the normalized dot product between two variables is called the Pearson correlation coefficient, and it is one of the most important analyses in data science


## Orthogonal

- orthogonal vectors have a dot product of zero (that claim goes both ways—​when the dot product is zero, then the two vectors are orthogonal). So, the following statements are equivalent: two vectors are orthogonal; two vectors have a dot product of zero; two vectors meet at a 90° angle. Repeat that equivalence until it’s permanently etched into your brain.


## Outer Product

- The outer product is quite different from the dot product: it produces a matrix instead of a scalar, and the two vectors in an outer product can have different dimensionalities, whereas the two vectors in a dot product must have the same dimensionality.

- The outer product is a way to create a matrix from a column vector and a row vector. Each row in the outer product matrix is the row vector scalar multiplied by the corresponding element in the column vector. We could also say that each column in the product matrix is the column vector scalar multiplied by the corresponding element in the row vector. 

## Orthogonal Vector Decomposition

- To “decompose” a vector or matrix means to break up that matrix into multiple simpler pieces. Decompositions are used to reveal information that is “hidden” in a matrix, to make the matrix easier to work with, or for data compression. It is no understatement to write that much of linear algebra (in the abstract and in practice) involves matrix decompositions. Matrix decompositions are a big deal.

- We can decompose the number 42.01 into two pieces: 42 and .01. Perhaps .01 is noise to be ignored, or perhaps the goal is to compress the data (the integer 42 requires less memory than the floating-point 42.01). Regardless of the motivation, the decomposition involves representing one mathematical object as the sum of simpler objects (42 = 42 + .01).

- We can decompose the number 42 into the product of prime numbers 2, 3, and 7. This decomposition is called prime factorization and has many applications in numerical processing and cryptography. This example involves products instead of sums, but the point is the same: decompose one mathematical object into smaller, simpler pieces.

## Example

In [1]:
import numpy as np

v = np.array([2, 1])
u = np.array([1, 3])

# Calculate the projection of v onto u
proj_u_v = (np.dot(v, u) / np.dot(u, u)) * u

# Calculate the orthogonal component of v with respect to u
orth_u_v = v - proj_u_v

proj_u_v, orth_u_v

(array([0.5, 1.5]), array([ 1.5, -0.5]))

## Exercise 2.2

In [3]:
import numpy as np
def compute_norm(v):
  
  squared_values = v**2
  sum_squares = np.sum(squared_values)
  norm = np.sqrt(sum_squares)
  return norm

np.random.seed(0)

vectors = [np.random.randn(n) for n in [5,10,15,20]]

for vec in vectors:
  custom_norm = compute_norm(vec)
  numpy_norm = np.linalg.norm(vec)
  print(f"Custom norm of vector ({len(vec)}-dimensional): {custom_norm}")
  print(f"NumPy norm of vector ({len(vec)}-dimensional): {numpy_norm}")

Custom norm of vector (5-dimensional): 3.5692169574087207
NumPy norm of vector (5-dimensional): 3.5692169574087207
Custom norm of vector (10-dimensional): 2.2330589116369346
NumPy norm of vector (10-dimensional): 2.2330589116369346
Custom norm of vector (15-dimensional): 4.823769201651546
NumPy norm of vector (15-dimensional): 4.823769201651546
Custom norm of vector (20-dimensional): 4.830458216740707
NumPy norm of vector (20-dimensional): 4.830458216740707


## Exercise 2.3

In [8]:
def to_unit_vector(v):
  
  norm = np.linalg.norm(v)
  if norm == 0.0:
    print("0 Vector cannot normalize")
    return v
  print(v/norm)

v1, v2 = np.array([2,3,4]), np.array([0,0,0])

unit_v1 = to_unit_vector(v1)
unit_v2 = to_unit_vector(v2)

[0.37139068 0.55708601 0.74278135]
0 Vector cannot normalize


## Exercise 2.4

#### You know how to create unit vectors; what if you want to create a vector of any arbitrary magnitude? Write a Python function that will take a vector and a desired magnitude as inputs and will return a vector in the same direction but with a magnitude corresponding to the second input.

In [14]:
def scale_vector(v, magnitude):
  
  norm = np.linalg.norm(v)
  
  if norm == 0:
    raise ValueError("Zero vector cannot be scaled to a non-zero magnitude")
  
  unit_vector = v/norm
  scaled_vector = unit_vector * magnitude
  return scaled_vector

v = np.array([3,4])
magnitude = 10

scaled_v = scale_vector(v, magnitude)
print("Original Vector:", v)
print("Scaled Vector:", scaled_v)
print("Magnitude of Scaled Vector:", np.linalg.norm(scaled_v))

Original Vector: [3 4]
Scaled Vector: [6. 8.]
Magnitude of Scaled Vector: 10.0


## Exercise 2-5.
#### Write a for loop to transpose a row vector into a column vector without using a built-in function or method such as np.transpose() or v.T. This exercise will help you create and index orientation-endowed vectors.

In [15]:
def transpose_vector(v):
  
  if v.ndim != 1:
    raise ValueError('Input must be an 1d row vector.')
  
  n = len(v)
  col_vector = np.zeros((n, 1))
  print(col_vector)
  
  for i in range(n):
    col_vector[i, 0] = v[i]
  
  return col_vector

row_vetor = np.array([1,2,3,4,5])
column_vector = transpose_vector(row_vetor)

print('Row Vector:')
print(row_vetor)

print("Transposed Vector")
print(column_vector)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Row Vector:
[1 2 3 4 5]
Transposed Vector
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


## Exercise 2-6.
#### Here is an interesting fact: you can compute the squared norm of a vector as the dot product of that vector with itself.

##### Calculating the squared norm using the dot product is often preferred in computational applications where the magnitude of a vector is compared or optimized, as it avoids the computational expense of taking a square root (as would be necessary for finding the actual norm). This technique is used in algorithms involving distances, optimizations, and similarity measures in machine learning, physics simulations, and more.

In [19]:
def squared_norm(v):
  
  return np.dot(v,v)

vector = np.array([3,4])
sq_norm = squared_norm(v)
norm = np.linalg.norm(vector) **2
print("Vector:", vector)
print("Squared Norm of the vector:", sq_norm)
print("Normalized Vector:", norm)


Vector: [3 4]
Squared Norm of the vector: 25
Normalized Vector: 25.0


## Exercise 2-7.

#### Write code to demonstrate that the dot product is commutative.

In [21]:
def check_communtativity(a,b):
  
  one = np.dot(a, b)
  two = np.dot(b,a)
  print(f"one: {one}, two: {two}")
  return one == two

a = np.array([2,3,4])
b = np.array([1,5,7])

print(check_communtativity(a,b))

one: 45, two: 45
True


## Exercise 2-9.
#### Implement orthogonal vector decomposition. Start with two random-number vectors